spring.application.name=strbll-file-upload
server.servlet.contextPath=/api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345

spring.datasource.url=jdbc:postgresql://localhost:5432/file_storage
storage.root-location=C:/root
security.api-key=123

spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false