spring.application.name=strbll-file-upload
server.servlet.contextPath=/api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/app_market?currentSchema=file
spring.datasource.username=postgres
spring.datasource.password=12345

storage.root-location=root